name: Christian Robert Shockley
favicon: null
layout_spectrum: null
typography_spectrum: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f0f19'
    - '#c02a22'
    - '#717957'
    - '#a4acae'
    - '#3b68b7'
  brandStrength: 1
  lightness: null
  saturation: null
  rhythmicContrast: null
purpose: []
