name: Christian Robert Shockley
favicon: null
layout_spectrum: 0.803
title: Christian Robert Shockley
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#262628'
    - '#e8dbc7'
    - '#8c9093'
    - '#87645a'
    - '#d39b81'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: shares
    item: null
    url: null
