name: Christian Robert Shockley
favicon: null
layout_spectrum: null
typography_spectrum: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e7e6e2'
    - '#021b3a'
    - '#6d859a'
    - '#0e496f'
    - '#93a6b6'
  brandStrength: 1
  lightness: null
  saturation: null
  rhythmicContrast: null
purpose: []
